/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_DiskJNI */

#ifndef _Included_jni_DiskJNI
#define _Included_jni_DiskJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_DiskJNI
 * Method:    insertUsr
 * Signature: (Lbase/model/Usr;)V
 */
JNIEXPORT void JNICALL Java_jni_DiskJNI_insertUsr
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jni_DiskJNI
 * Method:    deleteUsr
 * Signature: (Lbase/model/Usr;)V
 */
JNIEXPORT void JNICALL Java_jni_DiskJNI_deleteUsr
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jni_DiskJNI
 * Method:    updateUsr
 * Signature: (Lbase/model/Usr;)V
 */
JNIEXPORT void JNICALL Java_jni_DiskJNI_updateUsr
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jni_DiskJNI
 * Method:    selectUsr
 * Signature: (Lbase/model/Usr;)I
 */
JNIEXPORT jint JNICALL Java_jni_DiskJNI_selectUsr
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jni_DiskJNI
 * Method:    selectAllUsr
 * Signature: ()Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_jni_DiskJNI_selectAllUsr
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
